import type { Timestamp } from "firebase/firestore";

// ─── Settings ──────────────────────────────────────
export type Accent = "default" | "rose" | "emerald" | "amber";
export type Mode = "light" | "dark";

// ─── Difficulty ────────────────────────────────────
export type Difficulty =
	| "easy"
	| "normal"
	| "medium"
	| "hard"
	| "expert"
	| "master";

export type LabelledDifficulty = {
	id: Difficulty;
	label: string;
	desc: string;
};

// ─── Board ─────────────────────────────────────────
export type Board = (number | null)[][];
export type CellNotes = Set<number>[][];
export type DBCellNotes = Record<string, number[]>;
export type DBBoard = (number | null)[];

// ─── Puzzle ────────────────────────────────────────
export type Puzzle = {
	id: string;
	initial: Board;
	solution: Board;
	difficulty: Difficulty;
	score: number;
	techniques: string[];
	/** Present on puzzle data generated by the bounded logical grader. */
	techniqueAnalysis?: LogicalTechniqueAnalysis;
};

export type DBPuzzle = {
	id: string;
	puzzle: string;
	solution: string;
	difficulty: Difficulty;
	score: number;
	techniques: string[];
	techniqueAnalysis?: LogicalTechniqueAnalysis;
	updatedAt: Timestamp;
};

// ─── Game State ────────────────────────────────────
export type GameState = {
	puzzle: Puzzle;
	current: Board;
	notes: CellNotes;
	timer: number;
	actions: GameAction[];
	lastUpdated: Timestamp;
};

export type DBGameState = {
	puzzleId: string;
	initial: DBBoard;
	current: DBBoard;
	solution: DBBoard;
	difficulty: Difficulty;
	score: number;
	techniques: string[];
	techniqueAnalysis?: LogicalTechniqueAnalysis;
	timer: number;
	notes: DBCellNotes;
	actions: GameAction[];
	lastUpdated: Timestamp;
};

// ─── User Document ─────────────────────────────────
export type UserDocument = {
	settings: {
		accent: Accent;
		mode: Mode;
	};
	gameState: Omit<GameState, "lastUpdated"> | null;
	playedPuzzles?: string[];
};

export type DBUserDocument = {
	settings: {
		accent: Accent;
		mode: Mode;
	};
	gameState: DBGameState | null;
	playedPuzzles?: string[];
};

// ─── High Score ────────────────────────────────────
export type HighScore = {
	puzzle: Puzzle;
	time: number;
	date: Timestamp;
	userId: string;
	userName?: string;
	actions?: GameAction[];
};

export type DBHighScore = {
	difficulty: Difficulty;
	time: number;
	date: Timestamp;
	userId: string;
	userName?: string;
	initial?: DBBoard;
	solution?: DBBoard;
	actions?: GameAction[];
	puzzleId?: string;
	score?: number;
	techniques?: string[];
	techniqueAnalysis?: LogicalTechniqueAnalysis;
};

// ─── Game Actions ──────────────────────────────────
export type AddValueAction = {
	type: "addValue";
	delta: number;
	technique?: string;
	payload: {
		row: number;
		col: number;
		value: number;
	};
};

export type RemoveValueAction = {
	type: "removeValue";
	delta: number;
	technique?: string;
	payload: {
		row: number;
		col: number;
	};
};

export type AddNoteAction = {
	type: "addNote";
	delta: number;
	technique?: string;
	payload: {
		row: number;
		col: number;
		value: number;
	};
};

export type RemoveNoteAction = {
	type: "removeNote";
	delta: number;
	technique?: string;
	payload: {
		row: number;
		col: number;
		value: number;
	};
};

export type UndoAction = {
	type: "undo";
	delta: number;
};

export type RedoAction = {
	type: "redo";
	delta: number;
};

export type GameAction =
	| AddValueAction
	| RemoveValueAction
	| AddNoteAction
	| RemoveNoteAction
	| UndoAction
	| RedoAction;

// ─── Grading ───────────────────────────────────────
export interface GradedBoard {
	difficulty: number;
	techniquesUsed: Set<Technique>;
	isSolvable: boolean;
	solution: Board | null;
	actions: GameAction[];
}

/**
 * A serializable, solver-relative analysis of a puzzle's logical routes.
 *
 * "Minimum" deliberately refers to the lowest technique-score ceiling supported
 * by this grader. It is not a claim about every possible human solution.
 */
export type LogicalTechniqueRoute = {
	techniques: Technique[];
	/** Techniques at the minimum ceiling that were enabled for this route. */
	frontier: Technique[];
};

export type LogicalTechniqueAnalysis = {
	version: string;
	status: "solved-logically" | "search-needed";
	/** The ordinary deterministic route taken with every implemented technique. */
	observedTechniques: Technique[];
	/** Lowest base technique score whose complete supported set solved the puzzle. */
	minimumCeiling: number | null;
	/**
	 * Inclusion-minimal frontier configurations found exhaustively at that
	 * ceiling. All supported lower-scored techniques remain available.
	 */
	routes: LogicalTechniqueRoute[];
	/**
	 * Techniques whose individual removal made this bounded grader stall when
	 * every other technique at or below the minimum ceiling stayed available.
	 */
	unavoidableInReruns: Technique[];
};

export type Technique =
	| "Naked Single"
	| "Hidden Single"
	| "Naked Pair"
	| "Naked Triple"
	| "Hidden Pair"
	| "Hidden Triple"
	| "Naked Quad"
	| "Hidden Quad"
	| "Pointing Pairs"
	| "Line/Box Reduction"
	| "Gurth's Theorem"
	| "BUG+1"
	| "X-Wing"
	| "Skyscraper"
	| "2-String Kite"
	| "Unique Rectangle Type 1"
	| "Chute Remote Pair"
	| "Simple Colouring"
	| "Y-Wing"
	| "Rectangle Elimination"
	| "Swordfish"
	| "XYZ-Wing"
	| "Tridagon"
	| "X-Cycle"
	| "XY-Chain"
	| "3D Medusa"
	| "Jellyfish"
	| "Unique Rectangle 2,3,4,5"
	| "Avoidable Rectangle"
	| "Twinned XY-Chain"
	| "Fireworks"
	| "SK Loop"
	| "Extended Unique Rectangle"
	| "Hidden Unique Rectangle"
	| "WXYZ-Wing"
	| "Aligned Pair Exclusion"
	| "Exocet"
	| "Grouped X-Cycle"
	| "Finned X-Wing"
	| "Finned Swordfish"
	| "Franken Swordfish"
	| "Alternating Inference Chain"
	| "Sue-de-Coq"
	| "Digit Forcing Chain"
	| "Nishio Forcing Chain"
	| "Cell Forcing Chain"
	| "Unit Forcing Chain"
	| "Almost Locked Set"
	| "Death Blossom"
	| "Pattern Overlay"
	| "Quad Forcing Chain"
	| "Bowman Bingo"
	| "Backtracking";
